spring:
  application:
    name: User-Management-Service-Microservices
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://arunalubamunusinghe75:Arunalu123@cluster0.n5poqff.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: Snap-Eats
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

server:
  port: 8092
  servlet:
    context-path: /api/usermanager/
  error:
    include-exception: true
    include-message: always

token:
  signing:
    key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
logging:
  level:
    org.springframework: INFO
    edu.sliit: DEBUG